language: scala
scala:
  - 2.11.8
  - 2.10.6
jdk:
  - oraclejdk8
  - openjdk7

sudo: false

script: sbt test

notifications:
  emails:
    - ahne.ahne.ahne@gmail.com
  on_success: always
  on_failure: always